# Generated by Django 3.0.8 on 2020-07-28 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(blank=True, default=100, null=True, verbose_name='Сортировка')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('picture', models.ImageField(upload_to='blog', verbose_name='Картинка')),
                ('code', models.CharField(default='blog', max_length=500, unique=True, verbose_name='Код')),
                ('preview_text', models.TextField(blank=True, verbose_name='Превью текст')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('show_on_main_page', models.BooleanField(blank=True, default=False, null=True, verbose_name='Показывать на главной странице')),
                ('last_updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блог',
            },
        ),
        migrations.CreateModel(
            name='FormContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('subject', models.CharField(blank=True, max_length=500, verbose_name='Тема')),
                ('message', models.TextField(max_length=3000, verbose_name='Сообщение')),
                ('done', models.BooleanField(default=False, verbose_name='Обработано')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратные связи',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(blank=True, default=100, null=True, verbose_name='Сортировка')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('code', models.CharField(default='topic', max_length=500, unique=True, verbose_name='Код')),
                ('picture', models.ImageField(upload_to='gallery', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('show_on_main_page', models.BooleanField(blank=True, default=False, null=True, verbose_name='Показывать на главной странице')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(blank=True, default=100, null=True, verbose_name='Сортировка')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('picture', models.ImageField(upload_to='gallery', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('show_in_slider', models.BooleanField(blank=True, default=False, null=True, verbose_name='Показывать в слайдере')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rus.Topic', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
    ]
