# Generated by Django 3.0.8 on 2020-07-05 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(blank=True, default=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('picture', models.ImageField(upload_to='blog')),
                ('preview_text', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('show_on_main_page', models.BooleanField(blank=True, default=False, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(blank=True, default=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('code', models.CharField(default='topic', max_length=500)),
                ('picture', models.ImageField(upload_to='gallery')),
                ('description', models.TextField(blank=True)),
                ('show_on_main_page', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(blank=True, default=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('picture', models.ImageField(upload_to='gallery')),
                ('description', models.TextField(blank=True)),
                ('show_in_slider', models.BooleanField(blank=True, default=False, null=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rus_app.Topic')),
            ],
        ),
    ]
