# Generated by Django 3.0.8 on 2020-07-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rus_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='code',
            field=models.CharField(default='blog', max_length=500),
        ),
        migrations.AlterField(
            model_name='topic',
            name='code',
            field=models.CharField(default='topic', max_length=500, unique=True),
        ),
    ]
