# Generated by Django 2.2.12 on 2020-04-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rus_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='show_on_main_page',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='picture',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
