# Generated by Django 2.2.12 on 2020-04-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rus_app', '0002_auto_20200411_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='show_in_slider',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
