# Generated by Django 3.0.8 on 2020-07-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rus_app', '0002_auto_20200711_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='code',
            field=models.CharField(default='blog', max_length=500, unique=True),
        ),
    ]
