# Generated by Django 3.0.8 on 2020-07-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rus_app', '0003_auto_20200711_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('done', models.BooleanField(default=False)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
