# Generated by Django 3.0.8 on 2020-07-18 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rus_app', '0004_formcontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Блог', 'verbose_name_plural': 'Блог'},
        ),
        migrations.AlterModelOptions(
            name='formcontact',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратные связи'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галереи'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='code',
            field=models.CharField(default='blog', max_length=500, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.ImageField(upload_to='blog', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='preview_text',
            field=models.TextField(blank=True, verbose_name='Превью текст'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='show_on_main_page',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Показывать на главной странице'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='sort',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='formcontact',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='formcontact',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
        migrations.AlterField(
            model_name='formcontact',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='formcontact',
            name='message',
            field=models.TextField(blank=True, max_length=3000, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='formcontact',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='formcontact',
            name='subject',
            field=models.CharField(blank=True, max_length=500, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='picture',
            field=models.ImageField(upload_to='gallery', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='show_in_slider',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Показывать в слайдере'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='sort',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rus_app.Topic', verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='code',
            field=models.CharField(default='topic', max_length=500, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='picture',
            field=models.ImageField(upload_to='gallery', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='show_on_main_page',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Показывать на главной странице'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='sort',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название'),
        ),
    ]
