# Generated by Django 3.0.8 on 2020-07-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rus_app', '0005_auto_20200718_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
    ]
