# Generated by Django 3.0.8 on 2020-07-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rus_app', '0006_auto_20200718_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='formcontact',
            name='email',
            field=models.CharField(max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='formcontact',
            name='message',
            field=models.TextField(max_length=3000, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='formcontact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
    ]
